### PR TITLE
Use html-webpack-plugin@5 to work with webpack@5

### PR DESCRIPTION
**Pull request by ayukojohansson**
Plugin worked without change locally where html-webpack-plugin@5 is installed, so this should be enough to make it work with webpack🤞

### CODE REVIEW

**Review by jlowgren — CHANGES_REQUESTED** [review]
Thanks! Yarn lockfile needs updating.

`yarn install` should fix it.

**Comment by ayukojohansson** [comment]
Updated lock file now 👍

**Comment by jlowgren** [comment]
Sorry, vacation mode. You'll also need to update the commit format to follow commitlint. Since it's a potentially breaking change (hard to tell) it should be something like this:

```
# Commit title ⬇️
feat: use html-webpack-plugin@5 to work with webpack@5

# Commit message ⬇️ 
BREAKING CHANGE: New major version of Webpack
```

I also added a commitlint check to GitHub Actions to avoid confusion. It has to be formatted this way or release will fail.

**Comment by ayukojohansson** [comment]
Thanks @jlowgren for taking your time on this PR 🙏 
It's no urgent and please enjoy your vacation 🌴

**Comment by jlowgren** [comment]
> Thanks @jlowgren for taking your time on this PR 🙏 
> 
> It's no urgent and please enjoy your vacation 🌴 

No worries! I'll take another look when I get back from the wilderness.

**Review by jlowgren — APPROVED** [review]
LGTM 🙇

**Pull request merged**
